//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsedCarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_RolePoperdomInfo
    {
        public int RolePoerdomID { get; set; }
        public int RoleID { get; set; }
        public int PopedomId { get; set; }
    }
}
