//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsedCarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_PopedomInfo
    {
        public int PopedomId { get; set; }
        public string PopedomName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Url { get; set; }
        public Nullable<int> sortId { get; set; }
        public Nullable<int> ParentType { get; set; }
    }
}
