//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsedCarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Agents
    {
        public string Aid { get; set; }
        public string AName { get; set; }
        public string ATel { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string AddUser { get; set; }
        public Nullable<bool> isUsing { get; set; }
    }
}
