//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsedCarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CarOrder
    {
        public string OrderId { get; set; }
        public string CertType { get; set; }
        public string CertTypeOther { get; set; }
        public Nullable<decimal> KPPrice { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<System.DateTime> OrderAdddate { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public string OrderProcessStatus { get; set; }
        public string CustomerName { get; set; }
        public string CarId { get; set; }
        public Nullable<int> SHType { get; set; }
        public Nullable<System.DateTime> DJDate { get; set; }
        public string YHJD { get; set; }
        public string YCZXM { get; set; }
        public string YCZDH { get; set; }
        public string YCPHM { get; set; }
        public Nullable<bool> YSFDC { get; set; }
        public string XHJD { get; set; }
        public string XCZXM { get; set; }
        public string XCZDH { get; set; }
        public string XCPHM { get; set; }
        public Nullable<bool> XSFDC { get; set; }
        public string TCDD { get; set; }
        public string LXR { get; set; }
        public string LXRDH { get; set; }
        public Nullable<System.DateTime> YDDate { get; set; }
        public string Sales { get; set; }
        public string AddUser { get; set; }
        public string CarVIN { get; set; }
    }
}
