//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsedCarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CarInfo
    {
        public string CarId { get; set; }
        public string CarVIN { get; set; }
        public string CarModel { get; set; }
        public Nullable<System.DateTime> FirstOnCard { get; set; }
        public Nullable<int> ImgType { get; set; }
        public string ImgUrl { get; set; }
        public System.DateTime AddDate { get; set; }
        public string AddUser { get; set; }
        public bool isUsing { get; set; }
    }
}
