//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsedCarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CAR_BRAND
    {
        public int ID { get; set; }
        public string brandName { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string operateUser { get; set; }
        public string iconImg { get; set; }
        public Nullable<int> isValid { get; set; }
        public string firstPY { get; set; }
    }
}
