//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsedCarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_city
    {
        public int id { get; set; }
        public int cityID { get; set; }
        public string city { get; set; }
        public int fatherID { get; set; }
    }
}
