//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsedCarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Customer
    {
        public string CId { get; set; }
        public string CName { get; set; }
        public string Contacts { get; set; }
        public string CTel { get; set; }
        public string CAddress { get; set; }
        public string BelongUser { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string AddUser { get; set; }
        public bool isUsing { get; set; }
    }
}
