//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsedCarDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SEND
    {
        public int SendID { get; set; }
        public string SendNum { get; set; }
        public Nullable<int> SendType { get; set; }
        public bool State { get; set; }
        public string SendCode { get; set; }
        public string EquipContent { get; set; }
        public int UserId { get; set; }
        public string SendFunction { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string SendKey { get; set; }
    }
}
