//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsedCarDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UsedCarDBEntities : DbContext
    {
        public UsedCarDBEntities()
            : base("name=UsedCarDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin_PopedomInfo> Admin_PopedomInfo { get; set; }
        public DbSet<Admin_RoleInfo> Admin_RoleInfo { get; set; }
        public DbSet<Admin_RolePoperdomInfo> Admin_RolePoperdomInfo { get; set; }
        public DbSet<Admin_UserInfo> Admin_UserInfo { get; set; }
        public DbSet<Admin_UserInfoRole> Admin_UserInfoRole { get; set; }
        public DbSet<T_Agents> T_Agents { get; set; }
        public DbSet<T_CAR_BRAND> T_CAR_BRAND { get; set; }
        public DbSet<T_CarInfo> T_CarInfo { get; set; }
        public DbSet<T_CarInfo_Log> T_CarInfo_Log { get; set; }
        public DbSet<T_city> T_city { get; set; }
        public DbSet<T_Customer> T_Customer { get; set; }
        public DbSet<T_province> T_province { get; set; }
        public DbSet<T_SEND> T_SEND { get; set; }
        public DbSet<T_CarOrder> T_CarOrder { get; set; }
        public DbSet<View_OrderInfo> View_OrderInfo { get; set; }
    }
}
